CREATE TABLE messages (
    code    VARCHAR(4)   PRIMARY KEY,
    name    VARCHAR(50)  NOT NULL UNIQUE,
    message VARCHAR(255) NOT NULL
);

CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        UUID         NOT NULL UNIQUE,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    name        VARCHAR(100) NOT NULL,
    email       VARCHAR(150) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    last_login  TIMESTAMP    NOT NULL,
    token       VARCHAR(512) NOT NULL,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE phones (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid         UUID        NOT NULL UNIQUE,
    created_at   TIMESTAMP   NOT NULL,
    updated_at   TIMESTAMP   NOT NULL,
    number       VARCHAR(20) NOT NULL,
    city_code    VARCHAR(10) NOT NULL,
    country_code VARCHAR(10) NOT NULL,
    user_id      BIGINT      NOT NULL,
    CONSTRAINT fk_phones_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
